version: '3.9'

services:
  postgres_db_service:
    container_name: postgres_db_service
    image: postgres:11
    ports:
      - "5432:5432"
    hostname: postgres_db_service
    environment:
      - POSTGRES_PASSWORD=gowalk-pass
      - POSTGRES_USER=gowalk
      - POSTGRES_DB=gowalk-db